// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using OnibusExpress.Infrastructure.Context;

#nullable disable

namespace OnibusExpress.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260611214802_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("OnibusExpress.Domain.Entities.Passageiro", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Passageiros");
                });

            modelBuilder.Entity("OnibusExpress.Domain.Entities.Reserva", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CodigoReserva")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("NumeroAssento")
                        .HasColumnType("integer");

                    b.Property<Guid>("PassageiroId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("ViagemId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CodigoReserva")
                        .IsUnique();

                    b.HasIndex("PassageiroId");

                    b.HasIndex("ViagemId");

                    b.ToTable("Reservas");
                });

            modelBuilder.Entity("OnibusExpress.Domain.Entities.Rota", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Destino")
                        .HasColumnType("text");

                    b.Property<TimeSpan>("DuracaoEstimada")
                        .HasColumnType("interval");

                    b.Property<string>("Origem")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Rotas");
                });

            modelBuilder.Entity("OnibusExpress.Domain.Entities.Viagem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DataHoraPartida")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("PrecoBase")
                        .HasColumnType("numeric");

                    b.Property<Guid>("RotaId")
                        .HasColumnType("uuid");

                    b.Property<int>("TotalAssentos")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RotaId");

                    b.ToTable("Viagens");
                });

            modelBuilder.Entity("OnibusExpress.Domain.Entities.Passageiro", b =>
                {
                    b.OwnsOne("OnibusExpress.Domain.ValueObjects.Cpf", "Cpf", b1 =>
                        {
                            b1.Property<Guid>("PassageiroId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Numero")
                                .IsRequired()
                                .HasMaxLength(11)
                                .HasColumnType("character varying(11)")
                                .HasColumnName("Cpf");

                            b1.HasKey("PassageiroId");

                            b1.ToTable("Passageiros");

                            b1.WithOwner()
                                .HasForeignKey("PassageiroId");
                        });

                    b.Navigation("Cpf");
                });

            modelBuilder.Entity("OnibusExpress.Domain.Entities.Reserva", b =>
                {
                    b.HasOne("OnibusExpress.Domain.Entities.Passageiro", "Passageiro")
                        .WithMany()
                        .HasForeignKey("PassageiroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OnibusExpress.Domain.Entities.Viagem", "Viagem")
                        .WithMany()
                        .HasForeignKey("ViagemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Passageiro");

                    b.Navigation("Viagem");
                });

            modelBuilder.Entity("OnibusExpress.Domain.Entities.Viagem", b =>
                {
                    b.HasOne("OnibusExpress.Domain.Entities.Rota", "Rota")
                        .WithMany()
                        .HasForeignKey("RotaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rota");
                });
#pragma warning restore 612, 618
        }
    }
}
