version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: onibus_express_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: sua_senha_aqui
      POSTGRES_DB: onibus_express
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    image: onibus-express-api
    container_name: onibus_express_api
    build:
      context: ./backend
      dockerfile: src/OnibusExpress.Api/Dockerfile
    ports:
      - "5277:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=onibus_express;Username=postgres;Password=sua_senha_aqui
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data: